[package]
name = "allocators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.2"
rand = "0.8.5"
lock_api = "0.4.6"

[dev-dependencies]
parking_lot = { version = "0.12" }
